### ISSUE TITLE
delete a node from linked list

### ISSUE THREAD

**Issue by ayushjindal23** [rohithsprabhu/hacktoberfest2021-not-active-#345]
Hi, @rohithsprabhu  I would like to contribute to this repo and add program of deletion of node  in linked list in C++ .
Please assign this to me under Hacktoberfest2022 .
Thanks!!

**Comment by rohithsprabhu** [comment]
Sorry,
This is the Repo of hacktoberfest2021

Please pull requests to my hacktoberfest2022 Repo.
